# azure-pipelines.yml
trigger:
- main # Trigger pipeline on pushes to the main branch

variables:
  pythonVersion: '3.9' # Define Python version to use

stages:
- stage: Build_And_Test_Microsoft_Hosted
  displayName: 'Build & Test (Microsoft-Hosted)'
  jobs:
  - job: MicrosoftHostedJob
    displayName: 'Run on Microsoft-Hosted Agent'
    pool:
      vmImage: 'ubuntu-latest' # Using a Microsoft-hosted Ubuntu agent
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        pip install pytest
        pytest tests/
      displayName: 'Run unit tests with Pytest'

    # Mend Bolt Security Scan (runs after dependencies are installed)
    # Ensure Mend Bolt extension is installed in your Azure DevOps Org.
    - task: WhiteSource Bolt@21 # Or the latest version number for Mend Bolt
      displayName: 'Run Mend Bolt Security Scan'
      inputs:
        cwd: '$(System.DefaultWorkingDirectory)' # Scan the root of the checkout

- stage: Build_And_Test_Self_Hosted
  displayName: 'Build & Test (Self-Hosted)'
  dependsOn: Build_And_Test_Microsoft_Hosted # Ensure this runs after the MS-hosted stage
  condition: succeeded() # Only run if the previous stage succeeded
  jobs:
  - job: SelfHostedJob
    displayName: 'Run on Self-Hosted Agent'
    pool:
      name: 'MyLocalAgents' # Name of your self-hosted agent pool
      demands: [] # Add demands if needed, e.g., specific capabilities
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
        addToPath: true # Ensure Python is on PATH for subsequent scripts
      displayName: 'Use Python $(pythonVersion) (Self-Hosted)'
      condition: succeeded() # Only run if agent found

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies (Self-Hosted)'

    - script: |
        pip install pytest
        pytest tests/
      displayName: 'Run unit tests with Pytest (Self-Hosted)'
      
    # You can also run Mend Bolt here if you want to test its behavior
    # on a self-hosted agent, though it's typically run once per build.
    # - task: WhiteSource Bolt@21
    #   displayName: 'Run Mend Bolt Security Scan (Self-Hosted)'
    #   inputs:
    #     cwd: '$(System.DefaultWorkingDirectory)'